### Multipal String

In [3]:
massage ="""hey its me raihan nibir what's about you?
im a cse student """
print(massage)

hey its me raihan nibir what's about you?
im a cse student 


### Indexing And String

In [12]:
string = "hello world"
print(string[6])

w


### ND Array & Attributes

In [9]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array.ndim)

#Shape
print(array.shape)

# Data Type
print(array.dtype)

# Size
print(array.size)



1
(5,)
int64
5


### Data Type

In [12]:
#upcasting to float 
arr = np.array([1,2,3,4,5])
print(arr.dtype)

# upcasting to string
arr = np.array([1,2,3,4,5,'hello'])
print(arr.dtype)

int64
<U21


### ND Array Creation From Existing Data

In [3]:
import numpy as np

matrix = [
    [1, 2, 3],
    [4, 5, 6]
]

arr = np.array(matrix) 

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [ ]:
import numpy as np
lst = [ 10,20,30,40,40.5]
arr =np.array(lst, dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)

#### Creating NDarray From Scratch

In [22]:
#For zeros
import numpy as np
arr = np.zeros((2,3),dtype=np.int8)

print(arr)
print(arr.shape)

# For One

arr = np.ones_like((2,3),dtype=np.int8)

print(arr)
print(arr.shape)

# Empty 

arr = np.empty((4,3),dtype=np.int8)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)


[[0 0 0]
 [0 0 0]]
(2, 3)
[1 1]
(2,)
[[ -64    2   44]
 [-110  109    2]
 [   0    0    0]
 [   0    0    0]]
<class 'numpy.ndarray'>
(4, 3)
int8
2
12


#### Array Creation With Random Values 

In [21]:
arr = np.random.rand(2,3)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

[[0.10516209 0.67938564 0.36937773]
 [0.93867087 0.08782175 0.49471285]]
<class 'numpy.ndarray'>
(2, 3)
float64
2
6


#### Array Creation With Range Functions

In [31]:
# Scrial Number
arr = np.arange(1 , 10 , 1)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)
int64
1
9


In [25]:
# For Matrix
arr = np.arange(1 , 10 , 1)
mat = arr.reshape(3,3)
print(arr)
print(mat)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(9,)
int64
1
9


In [33]:
# Lin Space 
arr = np.linspace(1 , 10 , 10)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
(10,)
float64
1
10


In [34]:
# Log Space
arr = np.logspace(0, 4 , 6)
print(arr)


[1.00000000e+00 6.30957344e+00 3.98107171e+01 2.51188643e+02
 1.58489319e+03 1.00000000e+04]


#### Matrix For Linear Algebra

In [4]:
import numpy as np
diagonal_matrix = np.diag([1,2,3,4])
print(diagonal_matrix)
print(diagonal_matrix.shape)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [5]:
# identy matrix
import numpy as np
identity_mat = np.eye(4)
print(identity_mat)
print(identity_mat.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


  ### Stastitical Functions

In [8]:
# Load Data
import numpy as np

data = np.genfromtxt('students_marksheet.csv', delimiter=',', skip_header=1)
print(data)


[[101.  85.  90.  75.]
 [102.  78.  80.  88.]
 [103.  92.  85.  79.]
 [104.  88.  82.  95.]
 [105.  76.  70.  83.]]


In [10]:
# Sliceing
math_marks = data[::,1]
print (math_marks.T)

[85. 78. 92. 88. 76.]


In [12]:
# Max Number
max_math_marks = np.max(math_marks)
print("Hight Mark:" , max_math_marks)

Hight Mark: 92.0


In [16]:
# Minimum Number
min_math_marks = np.min(math_marks)
print("Lowest Marks:" , min_math_marks)

Lowest Marks: 76.0


In [18]:
# Average Number
average_math_marks = np.mean(math_marks)
print("Average Marks:" , average_math_marks)

Average Marks: 83.8


In [19]:
# Middle Number 
median_math_marks = np.median(math_marks)
print("Median Mrks:" , median_math_marks)

Median Mrks: 85.0


In [20]:
# Standerd Deviation
std_math_marks = np.std(math_marks)
print("Standerd Deviation:" , std_math_marks)

Standerd Deviation: 6.013318551349164
